### ISSUE TITLE
Investigate and fix broken Storybook stories in braze-components

### ISSUE THREAD

**Issue by SiAdcock** [guardian/storybooks#7]
```
Error: Failed to set a named property 'knobsData' on 'Window': Blocked a frame with origin "https://main--5f58cfe0c3997f00227756d7.chromatic.com" from accessing a cross-origin frame.
    at new KnobsData (https://main--5f58cfe0c3997f00227756d7.chromatic.com/561.475c4ce0.iframe.bundle.js:1:42182)
    at ./src/utils/knobsData.tsx (https://main--5f58cfe0c3997f00227756d7.chromatic.com/561.475c4ce0.iframe.bundle.js:1:41994)
    at __webpack_require__ (https://main--5f58cfe0c3997f00227756d7.chromatic.com/runtime~main.0a85fa27.iframe.bundle.js:1:381)
    at ./src/AUNewsletterEpic/index.stories.tsx (https://main--5f58cfe0c3997f00227756d7.chromatic.com/AUNewsletterEpic-index-stories.554a8a81.iframe.bundle.js:1:708)
    at __webpack_require__ (https://main--5f58cfe0c3997f00227756d7.chromatic.com/runtime~main.0a85fa27.iframe.bundle.js:1:381)
    at https://main--5f58cfe0c3997f00227756d7.chromatic.com/main.4d893a1e.iframe.bundle.js:1:8968
```
e.g. https://guardian.github.io/storybooks/?path=/docs/braze-components_endofarticle-aunewsletterepic--docs

Also seeing stories with the following error:
```
TypeError: Cannot read properties of undefined (reading 'set')
    at Object.StoryTemplate (https://main--5f58cfe0c3997f00227756d7.chromatic.com/Epic-index-stories.3b40179c.iframe.bundle.js:1:4498)
    at undecoratedStoryFn (https://main--5f58cfe0c3997f00227756d7.chromatic.com/sb-preview/runtime.js:113:5235)
    at hookified (https://main--5f58cfe0c3997f00227756d7.chromatic.com/sb-preview/runtime.js:97:10605)
    at https://main--5f58cfe0c3997f00227756d7.chromatic.com/sb-preview/runtime.js:113:3822
    at jsxDecorator (https://main--5f58cfe0c3997f00227756d7.chromatic.com/749.06f6f1a2.iframe.bundle.js:2:66507)
    at hookified (https://main--5f58cfe0c3997f00227756d7.chromatic.com/sb-preview/runtime.js:97:10605)
    at https://main--5f58cfe0c3997f00227756d7.chromatic.com/sb-preview/runtime.js:113:3361
    at https://main--5f58cfe0c3997f00227756d7.chromatic.com/sb-preview/runtime.js:113:4023
    at https://main--5f58cfe0c3997f00227756d7.chromatic.com/sb-preview/runtime.js:97:11408
    at unboundStoryFn (https://main--5f58cfe0c3997f00227756d7.chromatic.com/sb-preview/runtime.js:113:5798)
```
e.g. https://guardian.github.io/storybooks/?path=/story/braze-components_endofarticle-epicnewsletter-au-afternoonupdate--default-story

**Comment by sndrs** [comment]
can you expand a bit on this? we're not sure what needs doing/who should do it?
